// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atkyupcptzpoqqdihscr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0a3l1cGNwdHpwb3FxZGloc2NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwMzEzOTIsImV4cCI6MjA1MzYwNzM5Mn0.pSkPok6h1RhUSA3U8hfV5uKHv1o1HTFRwVO3ik2XY_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);